schema = 5
name = "CatOS Niri Noctaliav5"
description = "Complete CatOS Niri desktop powered by Noctalia"

packages = [
  "niri",
  "xdg-desktop-portal-gtk",
  "xdg-desktop-portal-gnome",
  "polkit-gnome",
  "power-profiles-daemon",
  "kitty",
  "xwayland-satellite",
  "tela-circle-icon-theme-all",
  "catos-bibata-cursor",
]

manage = [
  ".config/niri/config.kdl",
  ".config/kitty/kitty.conf",
  ".config/noctalia/config.toml",
  ".config/starship.toml",
]
