shell /usr/bin/fish

font_family		JetBrainsMono Nerd Font Mono
bold_font 		auto
italic_font		auto
bold_italic_font	auto
font_size		12.0

 
#windows
hide_window_decorations			titlebar-only
window_padding_width			15
background_opacity			0.50
background_blur				60

#tar bar
tab_bar_edge		top
tab_bara_style		powerline
tb_powerline_style	slanted

#cursor trail
cursor_trail 600
cursor_trail_decay 0.2 0.8
cursor_trail_color #769ff0
cursor_trail_start_threshold -1
cursor_shape block
cursor_integration no-cursor
