
[shell]
niri_overview_type_to_launch_enabled = true

[shell.panel]
transparency_mode = "glass"

[bar.main]
background_opacity = 0.5
start  = ["launcher", "wallpaper", "workspaces"]

[backdrop]
enabled = true
blur_intensity = 0.5
tint_intensity = 0.3

[theme.templates]
enable_builtin_templates = true
builtin_ids = ["gtk4", "gtk3", "qt", "niri"]

[shell.greeter_sync]
auto_sync = true
