[backdrop]
blur_intensity = 0.5
enabled = true
tint_intensity = 0.29999999999999999

[bar.main]
background_opacity = 0.5
start = [ "launcher", "wallpaper", "workspaces", "taskbar" ]

    [bar.main.dead_zone.actions]
    middle = "exec niri msg action close-window"
    scroll_down = "workspace-switch next"
    scroll_up = "workspace-switch prev"

[shell]
niri_overview_type_to_launch_enabled = true

    [shell.greeter_sync]
    auto_sync = true

    [shell.panel]
    transparency_mode = "glass"

[theme.templates]
builtin_ids = [ "gtk3", "gtk4", "niri", "qt" ]
enable_builtin_templates = true

